### PR TITLE
2.0.0 ullink

### PR DESCRIPTION
**Pull request by anaNadim**

### CODE REVIEW

**Comment by ngyukman** [comment]
Can you put down what has been done in this change?
and there is merge conflict that blocks the merge as well

**Review by josselinchevalay — APPROVED** [review]

**Comment by YanisLek** [comment]
Hi,
In this change we simply rebase the ullink-2.0.0 branch on the jolokia branch 2.0.

**Comment by ngyukman** [comment]
ok then please recreate a new merge commit, we should never do rebase in github as it is not supported
Right now there is conflict and no way to merge even I approve it

**Comment by anaNadim** [comment]
Hi @ngyukman  looks good now

**Review by ngyukman — APPROVED** [review]

**Pull request merged**
